### ISSUE TITLE
How to handle https://vm.tiktok.com/*/ URLs?

### ISSUE THREAD

**Issue by ltGuillaume** [pablouser1/tiktok-alt-frontend#2]
I'm not exactly "versed" in TikTok stuff on the web, I've never even been on a TikTok website/app, but I often get some URLs sent in a format like https://vm.tiktok.com/ZMRtL2yVX/

(How) can I use these in the front-end? Filling in ZMRtL2yVX as video ID just shows a blank page with nothing in the browser console, so I guess it needs to be processed in another way?

**Comment by pablouser1** [comment]
Hello, that is a url given by TikTok on Android/iOS and does not follow the same structure as the webapp version. This is not supported _yet_. The wrapper I currently use to make all the requests to TikTok doesn't have this situation in mind, but I'm working on a quick patch to support it.

**Comment by ltGuillaume** [comment]
Thanks, looking forward to it! I've browsed around a bit using a few tags and it's really nice 😃

**Comment by pablouser1** [comment]
Already deployed, thanks for pointing out the issue!

**Comment by ltGuillaume** [comment]
Thanks, it's working great!
