### ISSUE TITLE
Don't use Google Fonts

### ISSUE THREAD

**Issue by ltGuillaume** [pablouser1/tiktok-alt-frontend#3]
Using Google fonts with this kind of projects kind of defeats the purpose imho.

You can easily prevent connections to Google by including the fonts with the project itself. You can find webfonts on e.g. http://www.fontsquirrel.com or download from Google Fonts via https://google-webfonts-helper.herokuapp.com/fonts (although with the latter, I think you'd have to have a look at the license to see if you can indeed include the font with the project).

**Comment by pablouser1** [comment]
Hi, it looks like those fonts were imported by my CSS Framework, I didn't even noticed it until now 😂.
Fortunately it can be disabled using a SCSS variable (maybe I'll add a font without Google in the future).
I'll push a new build without Google Fonts, thanks for the help!
